### PR TITLE
Now students are removed from the queue when matched

### PR DESCRIPTION
**Pull request by Divineechidume**
We fixed out code to allow students to be removed from the queue when matched.

### CODE REVIEW

**Comment by an-ju** [comment]
Thanks for the quick fix!  However, it fails some cucumber tests locally.

```
Failing Scenarios:
cucumber features/admin_see_rating_tutors.feature:43 # Scenario: Admin can see rating tutor
cucumber features/admin_see_rating_tutors.feature:49 # Scenario: Tutor with multiple evaluations has average score
cucumber features/create_request_tutoring.feature:18 # Scenario: Request for tutoring - No privilege
cucumber features/create_request_tutoring.feature:33 # Scenario: Request for tutoring - With privilege
cucumber features/welcome_page.feature:24 # Scenario: login to my account successfully
cucumber features/welcome_page.feature:31 # Scenario: login to my account unsuccessfully
```

Please check this and fix the errors.  Besides, it would be great if you can add a few tests to cover this new feature / fix.  For example, a cucumber test that checks if a matched tutee is removed would be good.

**Comment by an-ju** [comment]
Tests are fixed by `rake db:reset`.  Can you add some test cases for removing tutee from the list once they're paired?

**Comment by Divineechidume** [comment]
Hi An, we have written more test and are ready to be pushed to the golden repo!

**Comment by an-ju** [comment]
Looks good to me.

**Pull request merged**
